Update setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,15 +1,25 @@
 #!/usr/bin/env bash
 
 ##############################
+#### SCRIPT CONFIGURATION
+##############################
+set -o errexit  # Exit immediately if a command exits with a non-zero status
+set -o nounset  # Treat unset variables as an error
+set -o pipefail # The return value of a pipeline is the status of the last command to exit with a non-zero status, or zero if no command exited with a non-zero status
+
+# Trap that will kill all background jobs when the script exits, ensuring the `sudo -v` loop is terminated
+trap 'kill $(jobs -p)' EXIT
+
+##############################
 #### CONSTANTS
 ##############################
-PLAIN='\033[0m'
-BOLD='\033[1m'
+readonly PLAIN='\033[0m'
+readonly BOLD='\033[1m'
 
-WHITE='\033[29m'
-GREEN='\033[32m'
-BLUE='\033[33m'
-RED='\033[31m'
+readonly WHITE='\033[29m'
+readonly GREEN='\033[32m'
+readonly BLUE='\033[33m'
+readonly RED='\033[31m'
 
 ##############################
 #### FUNCTIONS
@@ -23,25 +33,33 @@ clear_line(){
 }
 
 progress(){
-	if [ "$3" ]; then
-		echo -en "\033[0K$3 ["
+	local current_step="$1"
+	local total_steps="$2"
+	local message="$3"
+
+	if [ "$message" ]; then
+		echo -en "\033[0K$message ["
 	else
 		echo -en "\033[0K["
 	fi
-	for x in $(seq $1); do
+
+	local completed_bars=$(( ($current_step * 20) / $total_steps ))
+	local remaining_bars=$(( 20 - $completed_bars - 1 ))
+
+	for ((i=0; i<completed_bars; i++)); do
 		echo -ne "="
 	done
-	if [ ! $1 = $2 ]; then
+	if [ "$current_step" -lt "$total_steps" ]; then
 		echo -ne ">"
 	fi
-	for x in $(seq $(($2-$1-1))); do
+	for ((i=0; i<remaining_bars; i++)); do
 		echo -ne "."
 	done
 
 	echo -n "] "
-	printf "${BOLD}(%4s)${PLAIN}" "$((100*$1/$2))%"
+	printf "${BOLD}(%4s)${PLAIN}" "$((100 * $current_step / $total_steps))%"
 
-	if [ $1 = $2 ]; then
+	if [ "$current_step" -eq "$total_steps" ]; then
 		echo -ne "\n"
 	else
 		echo -ne "\r"
@@ -81,8 +99,10 @@ link_dotfile() {
 	local source="$1"
 	local destination="$2"
 
-	if [ -e "$destination" ]; then
-		fecho "Skipping: $destination already exists." $BLUE
+	if [ -L "$destination" ] && [ -e "$destination" ]; then
+		fecho "Skipping: $destination is a valid symlink." $BLUE
+	elif [ -e "$destination" ]; then
+		fecho "Skipping: $destination already exists (not a symlink)." $BLUE
 	else
 		ln -s "$source" "$destination"
 		if [ $? -eq 0 ]; then
@@ -94,42 +114,45 @@ link_dotfile() {
 }
 
 install_tool_managers() {
-	fecho "Installing SDKMAN..." $BLUE
+	fecho ""
+	fecho "Installing tool managers..." $BLUE
+
+	# SDKMAN
 	if [ ! -d "$HOME/.sdkman" ]; then
+		fecho "Installing SDKMAN..." $BLUE
 		curl -s "https://get.sdkman.io" | bash
 		fecho "SDKMAN has been installed." $GREEN
 	else
 		fecho "SDKMAN is already installed!" $GREEN
 	fi
 
-	fecho "Installing NVM..." $BLUE
-	# Use the specified NVM directory
+	# NVM
 	export NVM_DIR="$HOME/.config/nvm"
 	if [ ! -d "$NVM_DIR" ]; then
+		fecho "Installing NVM..." $BLUE
 		curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
 		fecho "NVM has been installed." $GREEN
 	else
 		fecho "NVM is already installed!" $GREEN
 	fi
 
-	fecho "Installing Pyenv..." $BLUE
-	# Use the specified Pyenv directory
+	# Pyenv
 	export PYENV_ROOT="$HOME/.pyenv"
 	if [ ! -d "$PYENV_ROOT" ]; then
+		fecho "Installing Pyenv..." $BLUE
 		curl -fsSL https://pyenv.run | bash
 		fecho "Pyenv has been installed." $GREEN
 	else
 		fecho "Pyenv is already installed!" $GREEN
 	fi
 
-	fecho
 	fecho "Tool managers installation complete!" $GREEN
 }
 
 ##############################
 #### MAIN SCRIPT
 ##############################
-fecho
+fecho ""
 fecho "Welcome..." $GREEN
 fecho "Let's set up this machine :)" $BLUE
 
@@ -139,21 +162,20 @@ if [[ "$user_input" != "y" && "$user_input" != "Y" ]]; then
 	exit 0
 fi
 
-fecho
+fecho ""
 fecho "Great! Let's start now..." $GREEN
-fecho
+fecho ""
 
 fecho "This script requires sudo privileges for installation..." $BLUE
 sudo -v
+while true; do sudo -n -v; sleep 60; done &>/dev/null &
 
-while true; do sudo -v; sleep 60; done &
-
-fecho
+fecho ""
 fecho "Updating the system..." $BLUE
-fecho
+fecho ""
 sudo apt update -y && sudo apt upgrade -y
 fecho "System update complete!" $GREEN
-fecho
+fecho ""
 
 fecho "Installing essential packages..." $BLUE
 if [ -f "packages.txt" ]; then
@@ -164,14 +186,13 @@ if [ -f "packages.txt" ]; then
 		clear_line
 		install_package "${packages[$i]}"
 		progress $(($i + 1)) $total "Installing packages"
-		sleep 1  # simulate time taken for installation
 	done
 else
 	fecho "Error: packages.txt file not found!" $RED
 	exit 1
 fi
 
-fecho
+fecho ""
 
 fecho "Installing snap packages..." $BLUE
 if [ -f "snap_packages.txt" ]; then
@@ -182,37 +203,36 @@ if [ -f "snap_packages.txt" ]; then
 		clear_line
 		install_snap_package "${snap_packages[$i]}"
 		progress $(($i + 1)) $total_snap "Installing snap packages"
-		sleep 1
 	done
 else
 	fecho "Error: snap_packages.txt file not found!" $RED
 	exit 1
 fi
 
-fecho
+fecho ""
 fecho "Changing default shell to Zsh..." $BLUE
 
-if [ "$(basename $SHELL)" != "zsh" ]; then
-	chsh -s $(which zsh)
-	fecho "Shell changed to Zsh!" $GREEN
+if [ "$(basename "$SHELL")" != "zsh" ]; then
+	chsh -s "$(which zsh)"
+	fecho "Shell changed to Zsh! Need to log out and back in for this to take effect." $GREEN
 else
 	fecho "Zsh is already the default shell!" $GREEN
 fi
 
-fecho
+fecho ""
 fecho "Setting up dotfiles..." $BLUE
-fecho
+fecho ""
 fecho "Linking top-level dotfiles..."
 link_dotfile "$HOME/.dotfiles/home/.zshenv" "$HOME/.zshenv"
 link_dotfile "$HOME/.dotfiles/home/.vimrc" "$HOME/.vimrc"
 
-fecho
+fecho ""
 fecho "Linking .local/bin files..."
 mkdir -p "$HOME/.local/bin"
 link_dotfile "$HOME/.dotfiles/home/.local/bin/sessionizer" "$HOME/.local/bin/sessionizer"
 link_dotfile "$HOME/.dotfiles/home/.local/bin/ssh-generate" "$HOME/.local/bin/ssh-generate"
 
-fecho
+fecho ""
 fecho "Linking XDG_CONFIG_HOME files..."
 export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
 mkdir -p "$XDG_CONFIG_HOME"
@@ -221,12 +241,11 @@ link_dotfile "$HOME/.dotfiles/xdg_config_home/git/config" "$XDG_CONFIG_HOME/git/
 link_dotfile "$HOME/.dotfiles/xdg_config_home/tmux/tmux.conf" "$XDG_CONFIG_HOME/tmux/tmux.conf"
 link_dotfile "$HOME/.dotfiles/xdg_config_home/zsh/.zshrc" "$XDG_CONFIG_HOME/zsh/.zshrc"
 
-fecho
+fecho ""
 fecho "Dotfiles symlinks completed!" $GREEN
-fecho
 
 install_tool_managers
 
-fecho
+fecho ""
 fecho "Setup complete!" $GREEN
 fecho "Reboot or log out for all changes to take effect!" $BLUE
